// Daily Dojo content — personalized to: Brazilian Jiu-Jitsu, cooking, Sydney life.
// Every item carries an example sentence; vocab is never introduced in isolation.
//
// Fields: id, lang, type (vocab|phrase|grammar), en (meaning), target,
//         kana/romaji (ja), note (optional), s: {t: sentence, r: romaji, en: translation}
// phrase/grammar items are tested as cloze: `target` must appear verbatim in s.t.

export const CONTENT_VERSION = 2;

export const ITEMS = [
  // ============================== 日本語 ==============================
  // --- BJJ / dojo ---
  { id:"ja01", lang:"ja", type:"vocab", en:"dojo / training hall", target:"道場", kana:"どうじょう", romaji:"doujou",
    s:{ t:"毎週火曜日に道場へ行く。", r:"maishuu kayoubi ni doujou e iku.", en:"I go to the dojo every Tuesday." } },
  { id:"ja02", lang:"ja", type:"vocab", en:"training / practice", target:"稽古", kana:"けいこ", romaji:"keiko",
    s:{ t:"今日の稽古はきつかった。", r:"kyou no keiko wa kitsukatta.", en:"Today's training was tough." } },
  { id:"ja03", lang:"ja", type:"vocab", en:"belt", target:"帯", kana:"おび", romaji:"obi",
    s:{ t:"帯をしっかり結ぶ。", r:"obi o shikkari musubu.", en:"Tie your belt properly." } },
  { id:"ja04", lang:"ja", type:"vocab", en:"breakfall", target:"受け身", kana:"うけみ", romaji:"ukemi",
    s:{ t:"まず受け身を練習しよう。", r:"mazu ukemi o renshuu shiyou.", en:"First, let's practice breakfalls." } },
  { id:"ja05", lang:"ja", type:"vocab", en:"ground fighting / ground techniques", target:"寝技", kana:"ねわざ", romaji:"newaza",
    s:{ t:"寝技の方が好きだ。", r:"newaza no hou ga suki da.", en:"I prefer groundwork." } },
  { id:"ja06", lang:"ja", type:"vocab", en:"choke", target:"絞め", kana:"しめ", romaji:"shime",
    s:{ t:"その絞めは本当に強い。", r:"sono shime wa hontou ni tsuyoi.", en:"That choke is really strong." } },
  { id:"ja07", lang:"ja", type:"vocab", en:"joint lock", target:"関節技", kana:"かんせつわざ", romaji:"kansetsuwaza",
    s:{ t:"関節技に気をつけて。", r:"kansetsuwaza ni ki o tsukete.", en:"Watch out for joint locks." } },
  { id:"ja08", lang:"ja", type:"vocab", en:"to throw", target:"投げる", kana:"なげる", romaji:"nageru",
    s:{ t:"先生は簡単に私を投げる。", r:"sensei wa kantan ni watashi o nageru.", en:"The teacher throws me easily." } },
  { id:"ja09", lang:"ja", type:"vocab", en:"to lock in / finish (a submission)", target:"極める", kana:"きめる", romaji:"kimeru",
    s:{ t:"やっと腕十字を極めた。", r:"yatto udejuuji o kimeta.", en:"I finally locked in the armbar." } },
  { id:"ja10", lang:"ja", type:"vocab", en:"injury", target:"怪我", kana:"けが", romaji:"kega",
    s:{ t:"怪我をしないように気をつけて。", r:"kega o shinai you ni ki o tsukete.", en:"Be careful not to get injured." } },
  { id:"ja11", lang:"ja", type:"vocab", en:"tired / exhausted (past)", target:"疲れた", kana:"つかれた", romaji:"tsukareta",
    s:{ t:"スパーリングの後で本当に疲れた。", r:"supaaringu no ato de hontou ni tsukareta.", en:"I was really tired after sparring." } },
  { id:"ja12", lang:"ja", type:"vocab", en:"strong", target:"強い", kana:"つよい", romaji:"tsuyoi",
    s:{ t:"相手はすごく強かった。", r:"aite wa sugoku tsuyokatta.", en:"My opponent was really strong." } },
  { id:"ja13", lang:"ja", type:"vocab", en:"to practice", target:"練習する", kana:"れんしゅうする", romaji:"renshuusuru",
    s:{ t:"毎日少しずつ練習する。", r:"mainichi sukoshi zutsu renshuu suru.", en:"I practice a little every day." } },
  { id:"ja14", lang:"ja", type:"vocab", en:"partner / opponent", target:"相手", kana:"あいて", romaji:"aite",
    s:{ t:"相手の動きをよく見て。", r:"aite no ugoki o yoku mite.", en:"Watch your opponent's movements carefully." } },
  { id:"ja15", lang:"ja", type:"phrase", en:"please / let's train (said before rolling)", target:"お願いします", kana:"おねがいします", romaji:"onegaishimasu",
    note:"Said with a bow before you start a roll.",
    s:{ t:"「お願いします」と言ってから組む。", r:"'onegaishimasu' to itte kara kumu.", en:"You say 'onegaishimasu' before you grip up." } },
  { id:"ja16", lang:"ja", type:"phrase", en:"one more round!", target:"もう一本", kana:"もういっぽん", romaji:"mouippon",
    s:{ t:"疲れたけど、もう一本！", r:"tsukareta kedo, mou ippon!", en:"I'm tired, but one more round!" } },
  { id:"ja17", lang:"ja", type:"phrase", en:"go easy on me, please", target:"ゆっくりお願いします", kana:"ゆっくりおねがいします", romaji:"yukkurionegaishimasu",
    s:{ t:"今日は肩が痛いから、ゆっくりお願いします。", r:"kyou wa kata ga itai kara, yukkuri onegaishimasu.", en:"My shoulder hurts today, so go easy on me please." } },

  // --- cooking / kitchen ---
  { id:"ja18", lang:"ja", type:"vocab", en:"soy sauce", target:"醤油", kana:"しょうゆ", romaji:"shouyu",
    s:{ t:"醤油を少しだけ入れる。", r:"shouyu o sukoshi dake ireru.", en:"Add just a little soy sauce." } },
  { id:"ja19", lang:"ja", type:"vocab", en:"dashi / soup stock", target:"出汁", kana:"だし", romaji:"dashi",
    s:{ t:"出汁から作ると美味しい。", r:"dashi kara tsukuru to oishii.", en:"It's delicious when you make the dashi from scratch." } },
  { id:"ja20", lang:"ja", type:"vocab", en:"kitchen knife", target:"包丁", kana:"ほうちょう", romaji:"houchou",
    s:{ t:"この包丁はよく切れる。", r:"kono houchou wa yoku kireru.", en:"This knife cuts really well." } },
  { id:"ja21", lang:"ja", type:"vocab", en:"to cut / chop", target:"切る", kana:"きる", romaji:"kiru",
    s:{ t:"玉ねぎを細かく切る。", r:"tamanegi o komakaku kiru.", en:"Chop the onion finely." } },
  { id:"ja22", lang:"ja", type:"vocab", en:"to grill / fry / bake", target:"焼く", kana:"やく", romaji:"yaku",
    s:{ t:"魚を焼く匂いがいい。", r:"sakana o yaku nioi ga ii.", en:"The smell of grilling fish is great." } },
  { id:"ja23", lang:"ja", type:"vocab", en:"to mix / stir", target:"混ぜる", kana:"まぜる", romaji:"mazeru",
    s:{ t:"全部よく混ぜてください。", r:"zenbu yoku mazete kudasai.", en:"Please mix everything well." } },
  { id:"ja24", lang:"ja", type:"vocab", en:"taste test", target:"味見", kana:"あじみ", romaji:"ajimi",
    s:{ t:"ちょっと味見してもいい？", r:"chotto ajimi shite mo ii?", en:"Can I have a little taste?" } },
  { id:"ja25", lang:"ja", type:"vocab", en:"low heat", target:"弱火", kana:"よわび", romaji:"yowabi",
    s:{ t:"弱火でゆっくり煮る。", r:"yowabi de yukkuri niru.", en:"Simmer it slowly on low heat." } },
  { id:"ja26", lang:"ja", type:"vocab", en:"to simmer / boil (food)", target:"煮る", kana:"にる", romaji:"niru",
    s:{ t:"野菜を三十分煮る。", r:"yasai o sanjuppun niru.", en:"Simmer the vegetables for thirty minutes." } },
  { id:"ja27", lang:"ja", type:"vocab", en:"fridge", target:"冷蔵庫", kana:"れいぞうこ", romaji:"reizouko",
    s:{ t:"冷蔵庫に何もない。", r:"reizouko ni nani mo nai.", en:"There's nothing in the fridge." } },
  { id:"ja28", lang:"ja", type:"vocab", en:"delicious", target:"美味しい", kana:"おいしい", romaji:"oishii",
    s:{ t:"この出汁、本当に美味しい！", r:"kono dashi, hontou ni oishii!", en:"This dashi is really delicious!" } },
  { id:"ja29", lang:"ja", type:"vocab", en:"sweet", target:"甘い", kana:"あまい", romaji:"amai",
    s:{ t:"このソースは少し甘い。", r:"kono soosu wa sukoshi amai.", en:"This sauce is a little sweet." } },
  { id:"ja30", lang:"ja", type:"vocab", en:"spicy / hot", target:"辛い", kana:"からい", romaji:"karai",
    s:{ t:"もっと辛いのが好き。", r:"motto karai no ga suki.", en:"I like it spicier." } },
  { id:"ja31", lang:"ja", type:"vocab", en:"salt", target:"塩", kana:"しお", romaji:"shio",
    s:{ t:"塩を入れすぎた！", r:"shio o iresugita!", en:"I added too much salt!" } },
  { id:"ja32", lang:"ja", type:"vocab", en:"rice / meal", target:"ご飯", kana:"ごはん", romaji:"gohan",
    s:{ t:"ご飯を炊くのを忘れた。", r:"gohan o taku no o wasureta.", en:"I forgot to cook the rice." } },
  { id:"ja33", lang:"ja", type:"phrase", en:"I'm hungry", target:"お腹すいた", kana:"おなかすいた", romaji:"onakasuita",
    s:{ t:"ああ、お腹すいた。早く食べよう。", r:"aa, onaka suita. hayaku tabeyou.", en:"Man, I'm hungry. Let's eat soon." } },

  // --- Sydney life ---
  { id:"ja34", lang:"ja", type:"vocab", en:"train", target:"電車", kana:"でんしゃ", romaji:"densha",
    s:{ t:"電車で街まで行く。", r:"densha de machi made iku.", en:"I take the train into the city." } },
  { id:"ja35", lang:"ja", type:"vocab", en:"station", target:"駅", kana:"えき", romaji:"eki",
    s:{ t:"駅の前で会いましょう。", r:"eki no mae de aimashou.", en:"Let's meet in front of the station." } },
  { id:"ja36", lang:"ja", type:"vocab", en:"sea / beach", target:"海", kana:"うみ", romaji:"umi",
    s:{ t:"日曜日は海に行きたい。", r:"nichiyoubi wa umi ni ikitai.", en:"I want to go to the beach on Sunday." } },
  { id:"ja37", lang:"ja", type:"vocab", en:"to swim", target:"泳ぐ", kana:"およぐ", romaji:"oyogu",
    s:{ t:"朝、海で泳ぐのが好きだ。", r:"asa, umi de oyogu no ga suki da.", en:"I like swimming in the sea in the morning." } },
  { id:"ja38", lang:"ja", type:"vocab", en:"hot (weather)", target:"暑い", kana:"あつい", romaji:"atsui",
    s:{ t:"今日は本当に暑いね。", r:"kyou wa hontou ni atsui ne.", en:"It's really hot today, isn't it?" } },
  { id:"ja39", lang:"ja", type:"vocab", en:"rain", target:"雨", kana:"あめ", romaji:"ame",
    s:{ t:"明日は雨らしい。", r:"ashita wa ame rashii.", en:"Apparently it'll rain tomorrow." } },
  { id:"ja40", lang:"ja", type:"vocab", en:"shopping", target:"買い物", kana:"かいもの", romaji:"kaimono",
    s:{ t:"土曜日の朝に買い物する。", r:"doyoubi no asa ni kaimono suru.", en:"I do the shopping on Saturday morning." } },
  { id:"ja41", lang:"ja", type:"vocab", en:"work / job", target:"仕事", kana:"しごと", romaji:"shigoto",
    s:{ t:"仕事の後で道場に行く。", r:"shigoto no ato de doujou ni iku.", en:"I go to the dojo after work." } },
  { id:"ja42", lang:"ja", type:"vocab", en:"busy", target:"忙しい", kana:"いそがしい", romaji:"isogashii",
    s:{ t:"今週はちょっと忙しい。", r:"konshuu wa chotto isogashii.", en:"This week is a bit busy." } },
  { id:"ja43", lang:"ja", type:"vocab", en:"weekend", target:"週末", kana:"しゅうまつ", romaji:"shuumatsu",
    s:{ t:"週末は何か予定ある？", r:"shuumatsu wa nanika yotei aru?", en:"Got any plans for the weekend?" } },
  { id:"ja44", lang:"ja", type:"vocab", en:"walk / stroll", target:"散歩", kana:"さんぽ", romaji:"sanpo",
    s:{ t:"海辺を散歩するのが好き。", r:"umibe o sanpo suru no ga suki.", en:"I like walking along the beach." } },
  { id:"ja45", lang:"ja", type:"vocab", en:"weather", target:"天気", kana:"てんき", romaji:"tenki",
    s:{ t:"今日はいい天気だね。", r:"kyou wa ii tenki da ne.", en:"Nice weather today, eh?" } },
  { id:"ja46", lang:"ja", type:"vocab", en:"crowded", target:"混んでいる", kana:"こんでいる", romaji:"kondeiru",
    s:{ t:"朝の電車はいつも混んでいる。", r:"asa no densha wa itsumo kondeiru.", en:"The morning train is always crowded." } },

  // --- grammar patterns (cloze) ---
  { id:"ja47", lang:"ja", type:"grammar", en:"want to swim (verb stem + たい = want to)", target:"泳ぎたい", kana:"およぎたい", romaji:"oyogitai",
    note:"stem + たい turns a verb into 'want to ~'",
    s:{ t:"暑いから、海で泳ぎたい。", r:"atsui kara, umi de oyogitai.", en:"It's hot, so I want to swim in the sea." } },
  { id:"ja48", lang:"ja", type:"grammar", en:"ate too much (〜すぎる = too much)", target:"食べすぎた", kana:"たべすぎた", romaji:"tabesugita",
    note:"stem + すぎる = to overdo",
    s:{ t:"昨日の夜、食べすぎた。", r:"kinou no yoru, tabesugita.", en:"I ate too much last night." } },
  { id:"ja49", lang:"ja", type:"grammar", en:"may I take (a photo)? (〜てもいいですか = may I?)", target:"撮ってもいいですか", kana:"とってもいいですか", romaji:"tottemoiidesuka",
    note:"て-form + もいいですか asks permission",
    s:{ t:"写真を撮ってもいいですか。", r:"shashin o totte mo ii desu ka.", en:"May I take a photo?" } },
  { id:"ja50", lang:"ja", type:"grammar", en:"have been (to) (〜たことがある = have done before)", target:"行ったことがある", kana:"いったことがある", romaji:"ittakotogaaru",
    note:"past + ことがある = past experience",
    s:{ t:"東京に行ったことがある。", r:"toukyou ni itta koto ga aru.", en:"I've been to Tokyo before." } },
  { id:"ja51", lang:"ja", type:"grammar", en:"I think it'll rain (〜と思う = I think)", target:"雨だと思う", kana:"あめだとおもう", romaji:"amedatoomou",
    s:{ t:"明日は雨だと思う。", r:"ashita wa ame da to omou.", en:"I think it'll rain tomorrow." } },
  { id:"ja52", lang:"ja", type:"grammar", en:"because I'm tired (〜から = because)", target:"疲れたから", kana:"つかれたから", romaji:"tsukaretakara",
    s:{ t:"疲れたから、早く寝る。", r:"tsukareta kara, hayaku neru.", en:"I'm tired, so I'm going to bed early." } },
  { id:"ja53", lang:"ja", type:"grammar", en:"am making (〜ている = ongoing action)", target:"作っている", kana:"つくっている", romaji:"tsukutteiru",
    s:{ t:"今、晩ご飯を作っている。", r:"ima, bangohan o tsukutteiru.", en:"I'm making dinner right now." } },
  { id:"ja54", lang:"ja", type:"grammar", en:"while listening (〜ながら = while doing)", target:"聞きながら", kana:"ききながら", romaji:"kikinagara",
    s:{ t:"音楽を聞きながら料理する。", r:"ongaku o kikinagara ryouri suru.", en:"I cook while listening to music." } },
  { id:"ja55", lang:"ja", type:"grammar", en:"do things like cooking (〜たり〜たり = things like)", target:"料理したり", kana:"りょうりしたり", romaji:"ryourishitari",
    s:{ t:"週末は料理したり、稽古したりする。", r:"shuumatsu wa ryouri shitari, keiko shitari suru.", en:"On weekends I do things like cooking and training." } },
  { id:"ja56", lang:"ja", type:"grammar", en:"before sleeping (〜前に = before doing)", target:"寝る前に", kana:"ねるまえに", romaji:"nerumaeni",
    s:{ t:"寝る前に、ストレッチをする。", r:"neru mae ni, sutorecchi o suru.", en:"I stretch before going to bed." } },

  // --- anime & watching shows (ord interleaves these into the new-item queue) ---
  { id:"ja57", lang:"ja", type:"vocab", en:"subtitles", target:"字幕", kana:"じまく", romaji:"jimaku", ord:2.5,
    s:{ t:"字幕なしでアニメを見るのが目標だ。", r:"jimaku nashi de anime o miru no ga mokuhyou da.", en:"Watching anime without subtitles is the goal." } },
  { id:"ja58", lang:"ja", type:"vocab", en:"comrades / crew (nakama)", target:"仲間", kana:"なかま", romaji:"nakama", ord:6.5,
    s:{ t:"ルフィにとって仲間が一番大事だ。", r:"rufi ni totte nakama ga ichiban daiji da.", en:"For Luffy, his crew matters most." } },
  { id:"ja59", lang:"ja", type:"vocab", en:"to give up", target:"諦める", kana:"あきらめる", romaji:"akirameru", ord:10.5,
    s:{ t:"ナルトは絶対に諦めない。", r:"naruto wa zettai ni akiramenai.", en:"Naruto never gives up." } },
  { id:"ja60", lang:"ja", type:"phrase", en:"I did it! / yes!", target:"やった", kana:"やった", romaji:"yatta", ord:14.5,
    s:{ t:"試合に勝って「やった！」と叫んだ。", r:"shiai ni katte 'yatta!' to sakenda.", en:"I won the match and shouted 'I did it!'" } },
  { id:"ja61", lang:"ja", type:"vocab", en:"training / ascetic practice (shugyō)", target:"修行", kana:"しゅぎょう", romaji:"shugyou", ord:18.5,
    note:"The anime-style word for hard training — works for BJJ too.",
    s:{ t:"強くなるために修行が必要だ。", r:"tsuyoku naru tame ni shugyou ga hitsuyou da.", en:"To get stronger, you need training." } },
  { id:"ja62", lang:"ja", type:"vocab", en:"signature / finishing move", target:"必殺技", kana:"ひっさつわざ", romaji:"hissatsuwaza", ord:22.5,
    s:{ t:"あのキャラの必殺技はかっこいい！", r:"ano kyara no hissatsuwaza wa kakko ii!", en:"That character's finishing move is so cool!" } },
  { id:"ja63", lang:"ja", type:"vocab", en:"enemy / opponent", target:"敵", kana:"てき", romaji:"teki", ord:26.5,
    s:{ t:"一番強い敵は自分だ。", r:"ichiban tsuyoi teki wa jibun da.", en:"The strongest enemy is yourself." } },
  { id:"ja64", lang:"ja", type:"vocab", en:"the continuation / what happens next", target:"続き", kana:"つづき", romaji:"tsuzuki", ord:30.5,
    s:{ t:"続きが気になって眠れない！", r:"tsuzuki ga ki ni natte nemurenai!", en:"I need to know what happens next — I can't sleep!" } },
  { id:"ja65", lang:"ja", type:"vocab", en:"giant / titan", target:"巨人", kana:"きょじん", romaji:"kyojin", ord:34.5,
    s:{ t:"進撃の巨人をもう一回見たい。", r:"shingeki no kyojin o mou ikkai mitai.", en:"I want to watch Attack on Titan again." } },
  { id:"ja66", lang:"ja", type:"vocab", en:"dubbed version (dub)", target:"吹き替え", kana:"ふきかえ", romaji:"fukikae", ord:38.5,
    s:{ t:"吹き替えより字幕の方が好き。", r:"fukikae yori jimaku no hou ga suki.", en:"I prefer subs over dubs." } },
  { id:"ja67", lang:"ja", type:"vocab", en:"protagonist / main character", target:"主人公", kana:"しゅじんこう", romaji:"shujinkou", ord:42.5,
    s:{ t:"この主人公は最初弱すぎる。", r:"kono shujinkou wa saisho yowasugiru.", en:"This protagonist is way too weak at first." } },
  { id:"ja68", lang:"ja", type:"vocab", en:"voice actor", target:"声優", kana:"せいゆう", romaji:"seiyuu", ord:46.5,
    s:{ t:"あの声優の声が大好きだ。", r:"ano seiyuu no koe ga daisuki da.", en:"I love that voice actor's voice." } },
  { id:"ja69", lang:"ja", type:"phrase", en:"no way! / it can't be!", target:"まさか", kana:"まさか", romaji:"masaka", ord:50.5,
    s:{ t:"まさか、あの二人が結婚？！", r:"masaka, ano futari ga kekkon?!", en:"No way — those two are getting married?!" } },
  { id:"ja70", lang:"ja", type:"grammar", en:"finished watching (〜終わる = finish doing)", target:"見終わった", kana:"みおわった", romaji:"miowatta", ord:54.5,
    s:{ t:"やっとシーズン一を見終わった。", r:"yatto shiizun ichi o miowatta.", en:"I finally finished watching season one." } },
  { id:"ja71", lang:"ja", type:"grammar", en:"did nothing but watch (〜てばかり = only/just doing)", target:"見てばかり", kana:"みてばかり", romaji:"mitebakari", ord:58.5,
    s:{ t:"週末はアニメを見てばかりいた。", r:"shuumatsu wa anime o mite bakari ita.", en:"All I did on the weekend was watch anime." } },

  // ============================== Español ==============================
  // --- BJJ / academia ---
  { id:"es01", lang:"es", type:"vocab", en:"to roll (spar)", target:"rodar",
    s:{ t:"Hoy quiero rodar con los cinturones morados.", en:"Today I want to roll with the purple belts." } },
  { id:"es02", lang:"es", type:"vocab", en:"the guard", target:"la guardia",
    s:{ t:"Tu guardia es muy difícil de pasar.", en:"Your guard is really hard to pass." } },
  { id:"es03", lang:"es", type:"vocab", en:"the choke", target:"el estrangulamiento",
    s:{ t:"Ese estrangulamiento desde la espalda es brutal.", en:"That choke from the back is brutal." } },
  { id:"es04", lang:"es", type:"vocab", en:"the lever / arm lock", target:"la palanca",
    s:{ t:"Casi consigo la palanca de brazo.", en:"I almost got the armbar." } },
  { id:"es05", lang:"es", type:"vocab", en:"to train", target:"entrenar",
    s:{ t:"Entreno jiu-jitsu tres veces por semana.", en:"I train jiu-jitsu three times a week." } },
  { id:"es06", lang:"es", type:"vocab", en:"the training partner", target:"el compañero",
    s:{ t:"Mi compañero de entrenamiento es muy técnico.", en:"My training partner is very technical." } },
  { id:"es07", lang:"es", type:"vocab", en:"to grab / grip", target:"agarrar",
    s:{ t:"Tienes que agarrar bien la solapa.", en:"You have to grip the lapel well." } },
  { id:"es08", lang:"es", type:"vocab", en:"to tap / give up", target:"rendirse",
    s:{ t:"Es mejor rendirse que lesionarse.", en:"Better to tap than to get injured." } },
  { id:"es09", lang:"es", type:"vocab", en:"to get injured", target:"lesionarse",
    s:{ t:"No quiero lesionarme antes del torneo.", en:"I don't want to get injured before the tournament." } },
  { id:"es10", lang:"es", type:"vocab", en:"to sweat", target:"sudar",
    s:{ t:"En verano sudo muchísimo en clase.", en:"In summer I sweat buckets in class." } },
  { id:"es11", lang:"es", type:"vocab", en:"the belt", target:"el cinturón",
    s:{ t:"Por fin me dieron el cinturón azul.", en:"They finally gave me my blue belt." } },
  { id:"es12", lang:"es", type:"vocab", en:"the technique", target:"la técnica",
    s:{ t:"Esa técnica funciona hasta con los grandotes.", en:"That technique works even on the big guys." } },
  { id:"es13", lang:"es", type:"vocab", en:"strong", target:"fuerte",
    s:{ t:"El nuevo es enorme y muy fuerte.", en:"The new guy is huge and really strong." } },
  { id:"es14", lang:"es", type:"vocab", en:"tired / worn out", target:"cansado",
    s:{ t:"Después de rodar estoy cansado pero feliz.", en:"After rolling I'm tired but happy." } },
  { id:"es15", lang:"es", type:"vocab", en:"the submission hold / lock", target:"la llave",
    s:{ t:"Me atrapó con una llave de brazo rapidísima.", en:"He caught me with a lightning-fast armlock." } },
  { id:"es16", lang:"es", type:"phrase", en:"let's roll!", target:"vamos a rodar",
    s:{ t:"Cinco minutos de descanso y ¡vamos a rodar!", en:"Five minutes' rest and let's roll!" } },
  { id:"es17", lang:"es", type:"phrase", en:"slowly, please / take it easy", target:"despacio, por favor",
    s:{ t:"Es mi primera clase, así que despacio, por favor.", en:"It's my first class, so take it slow please." } },

  // --- cocina ---
  { id:"es18", lang:"es", type:"vocab", en:"to chop / dice", target:"picar",
    s:{ t:"Primero hay que picar la cebolla.", en:"First you have to chop the onion." } },
  { id:"es19", lang:"es", type:"vocab", en:"the frying pan", target:"la sartén",
    s:{ t:"Calienta la sartén con un poco de aceite.", en:"Heat the pan with a bit of oil." } },
  { id:"es20", lang:"es", type:"vocab", en:"to boil", target:"hervir",
    s:{ t:"Pon el agua a hervir para la pasta.", en:"Put the water on to boil for the pasta." } },
  { id:"es21", lang:"es", type:"vocab", en:"to fry", target:"freír",
    s:{ t:"Voy a freír el pescado esta noche.", en:"I'm going to fry the fish tonight." } },
  { id:"es22", lang:"es", type:"vocab", en:"to mix", target:"mezclar",
    s:{ t:"Mezcla todo con la cuchara de madera.", en:"Mix everything with the wooden spoon." } },
  { id:"es23", lang:"es", type:"vocab", en:"to taste / try (food)", target:"probar",
    s:{ t:"¿Puedo probar la salsa?", en:"Can I taste the sauce?" } },
  { id:"es24", lang:"es", type:"vocab", en:"low heat", target:"el fuego lento",
    s:{ t:"Cocina el arroz a fuego lento veinte minutos.", en:"Cook the rice on low heat for twenty minutes." } },
  { id:"es25", lang:"es", type:"vocab", en:"the oil", target:"el aceite",
    s:{ t:"Este aceite de oliva es buenísimo.", en:"This olive oil is amazing." } },
  { id:"es26", lang:"es", type:"vocab", en:"the garlic", target:"el ajo",
    s:{ t:"Sin ajo no hay sabor.", en:"No garlic, no flavour." } },
  { id:"es27", lang:"es", type:"vocab", en:"the onion", target:"la cebolla",
    s:{ t:"La cebolla siempre me hace llorar.", en:"Onions always make me cry." } },
  { id:"es28", lang:"es", type:"vocab", en:"tasty / delicious", target:"rico",
    s:{ t:"¡Qué rico está este curry!", en:"This curry is so good!" } },
  { id:"es29", lang:"es", type:"vocab", en:"salty", target:"salado",
    s:{ t:"La sopa quedó demasiado salada.", en:"The soup came out too salty." } },
  { id:"es30", lang:"es", type:"vocab", en:"spicy", target:"picante",
    s:{ t:"Me encanta la comida picante.", en:"I love spicy food." } },
  { id:"es31", lang:"es", type:"vocab", en:"the fridge", target:"la nevera",
    s:{ t:"No queda casi nada en la nevera.", en:"There's almost nothing left in the fridge." } },
  { id:"es32", lang:"es", type:"vocab", en:"the recipe", target:"la receta",
    s:{ t:"Esta receta es de mi abuela.", en:"This recipe is my grandmother's." } },
  { id:"es33", lang:"es", type:"vocab", en:"the spoon", target:"la cuchara",
    s:{ t:"Pásame la cuchara grande, por favor.", en:"Pass me the big spoon, please." } },

  // --- vida en Sídney ---
  { id:"es34", lang:"es", type:"vocab", en:"the beach", target:"la playa",
    s:{ t:"El domingo vamos a la playa temprano.", en:"On Sunday we're going to the beach early." } },
  { id:"es35", lang:"es", type:"vocab", en:"to swim", target:"nadar",
    s:{ t:"Me gusta nadar antes del trabajo.", en:"I like swimming before work." } },
  { id:"es36", lang:"es", type:"vocab", en:"the wave", target:"la ola",
    s:{ t:"Las olas están enormes hoy.", en:"The waves are huge today." } },
  { id:"es37", lang:"es", type:"vocab", en:"the train", target:"el tren",
    s:{ t:"Tomo el tren al centro todos los días.", en:"I take the train to the city every day." } },
  { id:"es38", lang:"es", type:"vocab", en:"to get up early", target:"madrugar",
    s:{ t:"Odio madrugar los lunes.", en:"I hate getting up early on Mondays." } },
  { id:"es39", lang:"es", type:"vocab", en:"the work / job", target:"el trabajo",
    s:{ t:"Después del trabajo voy a entrenar.", en:"After work I go training." } },
  { id:"es40", lang:"es", type:"vocab", en:"busy", target:"ocupado",
    s:{ t:"Esta semana estoy demasiado ocupado.", en:"This week I'm way too busy." } },
  { id:"es41", lang:"es", type:"vocab", en:"the weekend", target:"el fin de semana",
    s:{ t:"¿Qué planes tienes el fin de semana?", en:"What plans do you have for the weekend?" } },
  { id:"es42", lang:"es", type:"vocab", en:"to go for a walk", target:"pasear",
    s:{ t:"Salimos a pasear por la costa.", en:"We went out for a walk along the coast." } },
  { id:"es43", lang:"es", type:"phrase", en:"it's hot (weather)", target:"hace calor",
    s:{ t:"Hoy hace calor de verdad.", en:"It's properly hot today." } },
  { id:"es44", lang:"es", type:"vocab", en:"to rain", target:"llover",
    s:{ t:"Parece que va a llover esta tarde.", en:"Looks like it's going to rain this afternoon." } },
  { id:"es45", lang:"es", type:"vocab", en:"the coffee", target:"el café",
    s:{ t:"Un café con leche para llevar, por favor.", en:"A café con leche to take away, please." } },
  { id:"es46", lang:"es", type:"phrase", en:"I do the grocery shopping (hacer la compra)", target:"hago la compra",
    s:{ t:"Los sábados hago la compra en el mercado.", en:"On Saturdays I do the shopping at the market." } },
  { id:"es47", lang:"es", type:"vocab", en:"to meet up (quedar)", target:"quedar",
    s:{ t:"¿Quedamos en la estación a las seis?", en:"Shall we meet at the station at six?" } },

  // --- Brooklyn 99 & The Office (ord interleaves these into the new-item queue) ---
  { id:"es58", lang:"es", type:"vocab", en:"the police precinct / station", target:"la comisaría", ord:2.5,
    s:{ t:"Brooklyn 99 pasa en una comisaría de Nueva York.", en:"Brooklyn 99 takes place in a New York precinct." } },
  { id:"es59", lang:"es", type:"vocab", en:"the detective", target:"el detective", ord:6.5,
    s:{ t:"Jake cree que es el mejor detective de Brooklyn.", en:"Jake thinks he's the best detective in Brooklyn." } },
  { id:"es60", lang:"es", type:"vocab", en:"the heist / robbery", target:"el atraco", ord:10.5,
    s:{ t:"¿Quién va a ganar el atraco de Halloween este año?", en:"Who's going to win the Halloween heist this year?" } },
  { id:"es61", lang:"es", type:"vocab", en:"the boss", target:"el jefe", ord:14.5,
    s:{ t:"Michael quiere ser el mejor jefe del mundo.", en:"Michael wants to be the world's best boss." } },
  { id:"es62", lang:"es", type:"vocab", en:"the prank / joke", target:"la broma", ord:18.5,
    s:{ t:"Jim siempre le hace bromas a Dwight.", en:"Jim is always playing pranks on Dwight." } },
  { id:"es63", lang:"es", type:"vocab", en:"the stapler", target:"la grapadora", ord:22.5,
    s:{ t:"Jim puso la grapadora de Dwight en gelatina.", en:"Jim put Dwight's stapler in jello." } },
  { id:"es64", lang:"es", type:"vocab", en:"the episode / chapter", target:"el capítulo", ord:26.5,
    s:{ t:"Anoche vimos tres capítulos de Brooklyn 99.", en:"Last night we watched three episodes of Brooklyn 99." } },
  { id:"es65", lang:"es", type:"vocab", en:"the beet", target:"la remolacha", ord:30.5,
    s:{ t:"Dwight tiene una granja de remolachas.", en:"Dwight has a beet farm." } },
  { id:"es66", lang:"es", type:"vocab", en:"the yogurt", target:"el yogur", ord:34.5,
    s:{ t:"A Terry le encanta el yogur.", en:"Terry loves yogurt." } },
  { id:"es67", lang:"es", type:"phrase", en:"that's what she said", target:"eso dijo ella", ord:38.5,
    s:{ t:"Michael siempre dice: «eso dijo ella».", en:"Michael always says: 'that's what she said'." } },
  { id:"es68", lang:"es", type:"phrase", en:"no doubt / without a doubt", target:"sin duda", ord:42.5,
    s:{ t:"¿El mejor detective? Jake, sin duda, sin duda.", en:"The best detective? Jake, no doubt, no doubt." } },
  { id:"es69", lang:"es", type:"grammar", en:"I keep watching — seguir + gerund", target:"Sigo viendo", ord:46.5,
    s:{ t:"Sigo viendo La Oficina por décima vez.", en:"I'm still watching The Office for the tenth time." } },
  { id:"es70", lang:"es", type:"grammar", en:"it makes me laugh — dar risa", target:"me da risa", ord:50.5,
    s:{ t:"Kevin con el chile siempre me da risa.", en:"Kevin with the chili always makes me laugh." } },

  // --- Kevin Kaarl (song-vocabulary strand — original sentences, not lyrics) ---
  { id:"es71", lang:"es", type:"vocab", en:"to miss (someone)", target:"extrañar", ord:4.5,
    s:{ t:"Las canciones de Kevin Kaarl son para extrañar a alguien.", en:"Kevin Kaarl's songs are for missing someone." } },
  { id:"es72", lang:"es", type:"vocab", en:"the lyrics", target:"la letra", ord:12.5,
    s:{ t:"Busqué la letra de «Amor Viejo» para cantarla.", en:"I looked up the lyrics of 'Amor Viejo' to sing along." } },
  { id:"es73", lang:"es", type:"phrase", en:"to the end of the world", target:"hasta el fin del mundo", ord:20.5,
    note:"Also the title of a Kevin Kaarl album.",
    s:{ t:"Iría contigo hasta el fin del mundo.", en:"I'd go with you to the end of the world." } },
  { id:"es74", lang:"es", type:"vocab", en:"old", target:"viejo", ord:28.5,
    s:{ t:"«Amor Viejo» es mi canción favorita de San Lucas.", en:"'Amor Viejo' is my favourite song from San Lucas." } },
  { id:"es75", lang:"es", type:"vocab", en:"to hug", target:"abrazar", ord:36.5,
    s:{ t:"Después de esa canción quiero abrazar a alguien.", en:"After that song I want to hug someone." } },
  { id:"es76", lang:"es", type:"vocab", en:"the farewell / goodbye", target:"la despedida", ord:44.5,
    s:{ t:"Sus canciones suenan a despedida.", en:"His songs sound like a farewell." } },
  { id:"es77", lang:"es", type:"grammar", en:"it reminds me of — recordar a", target:"me recuerda a", ord:52.5,
    s:{ t:"San Lucas me recuerda a un viaje por el desierto.", en:"San Lucas reminds me of a trip through the desert." } },
  { id:"es78", lang:"es", type:"grammar", en:"they make me want to — dar ganas de", target:"me dan ganas de", ord:56.5,
    s:{ t:"Sus canciones me dan ganas de llorar.", en:"His songs make me want to cry." } },

  // --- gramática (cloze) ---
  { id:"es48", lang:"es", type:"grammar", en:"I just (did) — acabar de + infinitive", target:"Acabo de",
    s:{ t:"Acabo de entrenar, dame un minuto.", en:"I just trained, give me a minute." } },
  { id:"es49", lang:"es", type:"grammar", en:"I'm going to — ir a + infinitive", target:"voy a",
    s:{ t:"Esta noche voy a cocinar curry japonés.", en:"Tonight I'm going to cook Japanese curry." } },
  { id:"es50", lang:"es", type:"grammar", en:"I have to — tener que + infinitive", target:"tengo que",
    s:{ t:"Mañana tengo que madrugar.", en:"Tomorrow I have to get up early." } },
  { id:"es51", lang:"es", type:"grammar", en:"I've been (doing) for — llevar + time + gerund", target:"Llevo",
    s:{ t:"Llevo dos años entrenando jiu-jitsu.", en:"I've been training jiu-jitsu for two years." } },
  { id:"es52", lang:"es", type:"grammar", en:"I forgot (accidentally) — se me olvidó", target:"Se me olvidó",
    s:{ t:"Se me olvidó la toalla otra vez.", en:"I forgot my towel again." } },
  { id:"es53", lang:"es", type:"grammar", en:"I am preparing — estar + gerund", target:"estoy preparando",
    s:{ t:"Ahora mismo estoy preparando la cena.", en:"Right now I'm making dinner." } },
  { id:"es54", lang:"es", type:"grammar", en:"I would like — me gustaría", target:"Me gustaría",
    s:{ t:"Me gustaría vivir más cerca de la playa.", en:"I'd like to live closer to the beach." } },
  { id:"es55", lang:"es", type:"grammar", en:"for (a duration) — desde hace + time", target:"desde hace",
    s:{ t:"Vivo en Sídney desde hace tres años.", en:"I've lived in Sydney for three years." } },
  { id:"es56", lang:"es", type:"grammar", en:"before (doing) — antes de + infinitive", target:"antes de",
    s:{ t:"Siempre estiro antes de entrenar.", en:"I always stretch before training." } },
  { id:"es57", lang:"es", type:"grammar", en:"I usually — soler + infinitive", target:"Suelo",
    s:{ t:"Suelo entrenar por la mañana.", en:"I usually train in the morning." } },
];
